name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # ✅ Deploy when pushing to 'main'
  workflow_dispatch:  # ✅ Allows manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # ✅ Needed for deployment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure index.html exists
        run: |
          if [ ! -f index.html ]; then
            echo "<h1>Welcome to GitHub Pages</h1>" > index.html
          fi

      - name: Deploy to GitHub Pages
        run: echo "GitHub Pages is enabled from the main branch."

      - name: Debugging
        run: echo "Deployment completed!"
