name: Daily Commit

on:
  schedule:
    - cron: '15 11 * * *'  # Runs at 00:00 UTC every day

jobs:
  update-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Updated to latest version
        with:
          fetch-depth: 0  # Fetch full history for proper merging

      - name: Set up Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Pull latest changes
        run: |
          git pull origin main --ff-only || echo "No need to pull"

      - name: Make changes
        run: |
          echo "Daily commit on $(date)" >> daily_commit.txt

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Daily commit on $(date)" || echo "No changes to commit"
          git push origin main

      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com  # Use your SMTP server
          server_port: 587
          username: ${{ secrets.EMAIL_USER }}  # Set in GitHub Secrets
          password: ${{ secrets.EMAIL_PASS }}  # Set in GitHub Secrets
          subject: "Daily Commit Successful"
          body: "A daily commit has been made on $(date)"
          to: "22f2001640@ds.study.iitm.ac.in"
          from: "GitHub Actions"
