name: Daily Commit

on:
  schedule:
    - cron: '30 0 * * *'  # Runs daily at 00:30 UTC (specific hour & minute)

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make changes
        run: |
          echo "Daily commit @ $(date)" >> daily_commit.txt

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add daily_commit.txt
          git commit -m "Daily commit on $(date)"
          git push

      - name: Notify 22f2001640@ds.study.iitm.ac.in
        run: echo "Commit made by GitHub Actions"
