name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # ✅ Runs when you push to 'main'
  workflow_dispatch:  # ✅ Allows manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # ✅ Needed for pushing to 'gh-pages'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Deploy to GitHub Pages
        run: |
          git checkout --orphan gh-pages
          git reset --hard
          git add index.html
          git commit -m "Deploy GitHub Pages"
          git push -f origin gh-pages  # ✅ Push to 'gh-pages' branch

      - name: Debugging
        run: echo "Deployment completed!"
